services:
  # 1. Database
  db:
    container_name: bot2_postgres
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_data_bot2:/var/lib/postgresql/data
    env_file:
      - .env

  # 2. REDIS (For states Ñ– FSM)
  redis:
    container_name: bot2_redis
    image: redis:7-alpine
    restart: always
    volumes:
      - redis_data_bot2:/data
    command: redis-server --save 60 1 --loglevel warning --maxmemory 200mb --maxmemory-policy allkeys-lru
  # 3. Bot (main logic)
  bot:
    container_name: bot2_worker
    build: .
    restart: always
    command: python bot.py
    volumes:
      - .:/app                 # We wake up the code so that the changes take effect immediately (for convenience).
      - media_data_bot2:/app/media  # Shared folder for photos/videos
    environment:
      - TZ=Europe/Berlin
    env_file:
      - .env
    depends_on:
      - db
      - redis

  # 4. DJANGO Admin (Web-interface)
  admin:
    container_name: bot2_admin
    build: .
    restart: always
    # Launch the admin server on 0.0.0.0 to view it externally
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - media_data_bot2:/app/media  # The same folder as the bot!
    environment:
      - TZ=Europe/Berlin
    ports:
      - "8001:8000"  # Opening the port to the outside world
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data_bot2:
  redis_data_bot2:
  media_data_bot2:  # Volume for storing lesson images